<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260901120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create orders, order_items, products and outbox tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE products (
            id VARCHAR(36) NOT NULL,
            name VARCHAR(255) NOT NULL,
            stock_quantity INT NOT NULL,
            min_threshold INT NOT NULL,
            price_amount INT NOT NULL,
            PRIMARY KEY(id)
        )');

        $this->addSql('CREATE TABLE orders (
            id VARCHAR(36) NOT NULL,
            customer_id VARCHAR(36) NOT NULL,
            status VARCHAR(20) NOT NULL,
            placed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY(id)
        )');

        $this->addSql('CREATE TABLE order_items (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            order_id VARCHAR(36) NOT NULL,
            product_id VARCHAR(36) NOT NULL,
            quantity_value INT NOT NULL,
            unit_price_amount INT NOT NULL,
            PRIMARY KEY(id)
        )');

        $this->addSql('CREATE INDEX idx_order_items_order_id ON order_items (order_id)');
        $this->addSql('CREATE INDEX idx_order_items_product_id ON order_items (product_id)');
        $this->addSql('ALTER TABLE order_items ADD CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE outbox (
            id VARCHAR(32) NOT NULL,
            type VARCHAR(255) NOT NULL,
            payload TEXT NOT NULL,
            occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            status VARCHAR(20) NOT NULL,
            PRIMARY KEY(id)
        )');

        $this->addSql('CREATE INDEX idx_outbox_status ON outbox (status)');
        $this->addSql('CREATE INDEX idx_outbox_occurred_at ON outbox (occurred_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE order_items');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE products');
        $this->addSql('DROP TABLE outbox');
    }
}
